spring:
  application:
    name: FinancialTransactions

  datasource:
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 30000
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/mydb
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: 123